# Generated by Django 5.1.2 on 2024-11-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.TextField(blank=True)),
                ("zip_code", models.TextField()),
                ("dob", models.DateField()),
                ("dor", models.DateField()),
                ("party_affiliation", models.TextField()),
                ("precinct_number", models.TextField()),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField(default=0)),
            ],
        ),
    ]
