# Generated by Django 5.1.2 on 2024-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="balance",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
