# Generated by Django 5.1.2 on 2024-11-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0003_student_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
