# Generated by Django 5.1.2 on 2024-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0004_remove_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(to="db_examples.course"),
        ),
    ]
