# Generated by Django 5.1.2 on 2024-11-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_examples", "0006_remove_student_courses_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("dob", models.DateField()),
                (
                    "father",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="father_of",
                        to="db_examples.familyperson",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mother_of",
                        to="db_examples.familyperson",
                    ),
                ),
            ],
        ),
    ]
